import { TimetableToday, Timetable, TemplateInfoFull } from './types'


export const testWeekTableData: Timetable = {
    1: {
        1: {
            week: '1',
            day: '1',
            order: '1',
            room: 'D212',
            subject: 'Математическая логика и теория алгоритмов',
            type: 'lecture',
            teacher: 'Черныш Елена Валерьевна',
            homework: 'Сделать ИДЗ',
            'test': false,
            'project': false,
            'colloquium': true,
        },
        2: {
            week: '1',
            day: '1',
            order: '2',
            room: 'D212',
            subject: 'Программная инженерия',
            type: 'lecture',
            teacher: 'Скурский Степан Валерьевич',
            'test': true,
            'project': false,
            'colloquium': false,
        },
    },
    2: {
        2: {
            week: '1',
            day: '2',
            order: '2',
            room: 'D207',
            subject: 'Аналитическая геометрия и компьютерная графика',
            type: 'lecture',
            teacher: 'Гузев Михаил Александрович',
            test: false,
            project: false,
            colloquium: false,
        },
        5: {
            week: '1',
            day: '2',
            order: '5',
            room: 'D659',
            subject: 'Алгоритмы и структуры данных',
            type: 'practice',
            teacher: 'Малыкина Ирина Анатольевна',
            'test': false,
            'project': true,
            'colloquium': false,
        },
        6: {
            week: '1',
            day: '2',
            order: '6',
            room: 'S',
            subject: 'Физкультура',
            type: 'practice',
            homework: 'Написать конспект',
            test: false,
            project: false,
            colloquium: false,
        },
    },
    3: {
        3: {
            week: '1',
            day: '3',
            order: '3',
            room: 'D447',
            subject: 'Программная инженерия',
            type: 'practice',
            teacher: 'Скурский Степан Андреевич',
            'test': false,
            'project': true,
            'colloquium': true,
        },
        4: {
            week: '1',
            day: '3',
            order: '4',
            room: 'D546a',
            subject: 'Программная инженерия',
            type: 'practice',
            teacher: 'Скурский Степан Андреевич',
            'test': true,
            'project': false,
            'colloquium': true,
    
        },
        6: {
            week: '1',
            day: '3',
            order: '6',
            room: 'D818',
            subject: 'Математическая логика и теория алгоритмов',
            type: 'practice',
            teacher: 'Черныш Елена Валерьевна',
            test: false,
            project: false,
            colloquium: false,
        },
    },
    4: {},
    5: {
        1: {
            week: '1',
            day: '5',
            order: '1',
            room: 'D212',
            subject: 'Дифференциальные уравнения',
            type: 'lecture',
            teacher: 'Чеботарев Александр Юрьевич',
            test: false,
            project: false,
            colloquium: false,
        },
        3: {
            week: '1',
            day: '5',
            order: '3',
            room: 'E236',
            subject: 'Теория вероятности и математическая статистика',
            type: 'lecture',
            teacher: 'Тарасова Ирина Михайловна',
            'test': false,
            'project': false,
            'colloquium': true,
        },
        4: {
            week: '1',
            day: '5',
            order: '4',
            room: 'D504',
            subject: 'Теория вероятности и математическая статистика',
            type: 'practice',
            teacher: 'Тарасова Ирина Михайловна',
            'test': true,
            'project': false,
            'colloquium': false,
        },
        5: {
            week: '1',
            day: '5',
            order: '5',
            room: 'D654',
            subject: 'Алгоритмы и структуры данных',
            type: 'lecture',
            teacher: 'Малыкина Ирина Анатольевна',
            test: false,
            project: false,
            colloquium: false,
        },
        6: {
            week: '1',
            day: '5',
            order: '6',
            room: 'S',
            subject: 'Физкультура',
            type: 'practice',
            teacher: 'Светлана Анатольевна',
            test: false,
            project: false,
            colloquium: false,
        },
    },
    6: {
        1: {
            week: '1',
            day: '6',
            order: '1',
            room: 'D738',
            subject: 'Основы теории кодирования',
            type: 'lecture',
            teacher: 'Серга Ирина Викторовна',
            test: false,
            project: false,
            colloquium: false,
        },
        2: {
            week: '1',
            day: '6',
            order: '2',
            room: 'D656',
            subject: 'Основы теории кодирования',
            type: 'practice',
            teacher: 'Серга Ирина Викторовна',
            test: false,
            project: false,
            colloquium: false,
        },
        3: {
            week: '1',
            day: '6',
            order: '3',
            room: 'D809',
            subject: 'Аналитическая геометрия и компьютерная графика',
            type: 'practice',
            teacher: 'Курочкина Ирина Алексеевна',
            test: false,
            project: false,
            colloquium: false,
        },
        4: {
            week: '1',
            day: '6',
            order: '4',
            room: 'E715',
            subject: 'Безопасность жизнедеятельности',
            type: 'practice',
            teacher: 'Некто Рандом',
            test: false,
            project: false,
            colloquium: false,
        },
    },
}

export const testTodayTableData: TimetableToday = {
    1: {
        week: '1',
        day: '1',
        order: '1',
        room: 'D212',
        subject: 'Математическая логика и теория алгоритмов',
        type: 'lecture',
        teacher: 'Черныш Елена Валерьевна',
        'test': false,
        'project': false,
        'colloquium': true,
    },
    2: {
        week: '1',
        day: '1',
        order: '2',
        room: 'D212',
        subject: 'Программная инженерия',
        type: 'lecture',
        teacher: 'Скурский Степан Валерьевич',
        'test': true,
        'project': false,
        'colloquium': false,
    },
}

export const testTemplatesData: {[key: string]: TemplateInfoFull} = {
    1: {
        id: 'chet',
        name: 'Чётные страдания',
        description: 'Данный круг ада содержит в себе дифференциальные уравнения и физику, поэтому нельзя расслаблять булки.'
    },
    2: {
        id: 'nechet',
        name: 'Нечётное блаженство',
        description: 'На этой неделе можно расслабиться, ибо расписание чилловое.'
    },
    3: {
        id: 'test',
        name: 'Тестовый шаблон',
    }
}